### ISSUE TITLE
Events.Broadcast additional args

### ISSUE THREAD

**Issue by StanzillaManticore** [kerwanp/core-types-generator#11]
Events.Broadcast and other functions that can have any number of arguments after the mandatory ones currently complain about having too many. Not sure if this is is a definition file or LSP issue

![image](https://user-images.githubusercontent.com/58569561/126065992-a2f52c90-463d-4e10-af76-f5f2fa8623eb.png)

**Comment by kerwanp** [comment]
I've added the support for variadic functions, you can grab the new release
