### ISSUE TITLE
Missing Constants

### ISSUE THREAD

**Issue by StanzillaManticore** [kerwanp/core-types-generator#2]
The definition file is currently missing all constants, these are in the JSON dump as 

```json
"Constants": [
				{
					"Name": "ZERO",
					"Description": "(0, 0, 0)",
					"Type": "Vector3"
				},
				{
					"Name": "ONE",
					"Description": "(1, 1, 1)",
					"Type": "Vector3"
				},
				{
					"Name": "FORWARD",
					"Description": "(1, 0, 0)",
					"Type": "Vector3"
				},
				{
					"Name": "UP",
					"Description": "(0, 0, 1)",
					"Type": "Vector3"
				},
				{
					"Name": "RIGHT",
					"Description": "(0, 1, 0)",
					"Type": "Vector3"
				}
			],
```

for example.

**Comment by kerwanp** [comment]
@StanzillaManticore It will be pretty straight forward but is there any reason for not using enums ?

**Comment by StanzillaManticore** [comment]
@kerwanp Was probably some implementation detail. Probably hard to change now but I can ask for in the future.

**Comment by StanzillaManticore** [comment]
@kerwanp I updated our extension but still get 

```
Undefined field `FORWARD`
```

from the Lua LSP when doing something like `local test = Vector3.FORWARD`, is that a bug in the server then?
